### PR TITLE
Expanded the capabilities of the PushAPI

### PR DESCRIPTION
**Pull request by brianlangeland**
Changes included:
Downgraded codebase to Java 11. This mostly entailed altering records to traditional Java classes.
Added missing endpoint integrations, particularly for pushing batches of Security Identities, deleting documents, pushing binary files to a File Container, and setting Push API Status.
Added support for multiple environments, each having a different domain.

### CODE REVIEW

**Comment by louis-bompart** [comment]
Hi @brianlangeland , thanks for the contribution, looks good overall 👍 

I'm a bit dubious concerning the downgrade from Java 16 to 11, what does motivate the downgrade in your opinion?

**Comment by brianlangeland** [comment]
There were two reasons why I needed to downgrade the Java version to 11:
1) The project that will utilize this API is built on Java 11. I'm not able to update it to Java 16 because...
2) The end application it will all build into runs an OSGi 11 container. The OSGi container would not permit a bundle compiled in a newer version of Java from installing/running (trust me, I tried).

**Comment by louis-bompart** [comment]
> There were two reasons why I needed to downgrade the Java version to 11:
> 
> 1. The project that will utilize this API is built on Java 11. I'm not able to update it to Java 16 because...
> 2. The end application it will all build into runs an OSGi 11 container. The OSGi container would not permit a bundle compiled in a newer version of Java from installing/running (trust me, I tried).

Hey @brianlangeland , thanks for your answer, I've been documenting myself a bit on the matter.

You're totally right, we should support Java 11, Java 16 is way too early in its adoption. 👍 

I checked your changes, they seem fine to me, but for clarity's sake, I'd like you to separate this PR into two if that's okay with you;  One for the new Java Version, another for the new endpoints.

Thanks a lot again for your contr> There were two reasons why I needed to downgrade the Java version to 11:
> 
> 1. The project that will utilize this API is built on Java 11. I'm not able to update it to Java 16 because...
> 2. The end application it will all build into runs an OSGi 11 container. The OSGi container would not permit a bundle compiled in a newer version of Java from installing/running (trust me, I tried).

Hey @brianlangeland , thanks for your answer, I've been documenting myself a bit on the matter.

You're totally right, we should support Java 11, Java 16 is way too early in its adoption. 👍 

I checked your changes, they seem fine to me, but for clarity's sake, I'd like you to separate this PR into two if that's okay with you;  ​One for the new Java Version, another for the new endpoints.

Thanks again for your contribution 👍

**Comment by brianlangeland** [comment]
I've created [this new PR](https://github.com/coveo/push-api-client.java/pull/19) to handle the shift to Java 11. Once that is merged, I will push an update to this branch/PR which will include just the API changes.

**Comment by brianlangeland** [comment]
I've updated this branch to just have the remaining changes for the new endpoint functionality, etc, and it is now ready for review.

**Pull request merged**
